
package bibliotheque.view;

import bibliotheque.view.customComponents.BgPanel;
import bibliotheque.view.customComponents.CustomListCellRenderer;
import bibliotheque.model.DBConnection;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.border.Border;
import javax.swing.plaf.basic.BasicSplitPaneDivider;
import javax.swing.plaf.basic.BasicSplitPaneUI;

/**
 *
 * @author shiro
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public MainFrame() {
        
        setTitle("Bibliothèque");
        try {
            littleBird = Font.createFont(Font.TRUETYPE_FONT, getClass().getClassLoader().getResourceAsStream("LittleBird.ttf"));
        } catch (FontFormatException | IOException ex) {
            Logger.getLogger(BgPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            clearLine = Font.createFont(Font.TRUETYPE_FONT, getClass().getClassLoader().getResourceAsStream("ClearLine.ttf"));
        } catch (FontFormatException | IOException ex) {
            Logger.getLogger(BgPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            glyphicons = Font.createFont(Font.TRUETYPE_FONT, getClass().getClassLoader().getResourceAsStream("glyphicons.ttf"));
        } catch (FontFormatException | IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            maritime = Font.createFont(Font.TRUETYPE_FONT, getClass().getClassLoader().getResourceAsStream("MaritimeTropicalNeue.ttf"));
        } catch (FontFormatException | IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new BgPanel();
        workingArea = new javax.swing.JPanel();
        L_title = new javax.swing.JLabel();
        controls = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        toggleButtons = new javax.swing.JPanel();
        TB_card1 = new javax.swing.JToggleButton();
        TB_card2 = new javax.swing.JToggleButton();
        TB_card3 = new javax.swing.JToggleButton();
        TB_card4 = new javax.swing.JToggleButton();
        mainMenuButtons = new javax.swing.JPanel();
        B_webSite = new javax.swing.JButton();
        B_settings = new javax.swing.JButton();
        B_help = new javax.swing.JButton();
        B_quit = new javax.swing.JButton();
        tabGroups = new javax.swing.JPanel();
        defaultTab = new javax.swing.JPanel();
        P_titles = new javax.swing.JPanel();
        L_title1 = new javax.swing.JLabel();
        L_title2 = new javax.swing.JLabel();
        tab1 = new javax.swing.JPanel();
        L_title_tab1 = new javax.swing.JLabel();
        controls_tab1 = new javax.swing.JPanel();
        fields_tab1 = new javax.swing.JPanel();
        fields_tab1_top = new javax.swing.JPanel();
        L_bookTitle_fields_tab1 = new javax.swing.JLabel();
        L_name_fields_tab1 = new javax.swing.JLabel();
        nameFields_fields_tab1 = new javax.swing.JPanel();
        SP_pupilList_tab1 = new javax.swing.JScrollPane();
        Li_pupilList_tab1 = new javax.swing.JList<>();
        TF_name_nameFields_tab1 = new javax.swing.JTextField();
        TF_surname_nameFields_tab1 = new javax.swing.JTextField();
        fields_tab1_btm = new javax.swing.JPanel();
        B_validate_fields_tab1 = new javax.swing.JButton();
        scan_tab1 = new javax.swing.JPanel();
        F_paging_scan_tab1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        scanFrame_tab1 = new javax.swing.JPanel();
        L_scanFrame_title_tab1 = new javax.swing.JLabel();
        controls_scanFrame_tab1 = new javax.swing.JPanel();
        FTF_barCode_tab1 = new javax.swing.JFormattedTextField();
        B_validate_scanFrame_tab1 = new javax.swing.JButton();
        tab2 = new javax.swing.JPanel();
        L_title_tab2 = new javax.swing.JLabel();
        scan_tab2 = new javax.swing.JPanel();
        F_paging_scan_tab2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        scanFrame_tab2 = new javax.swing.JPanel();
        L_title_scanFrame_tab2 = new javax.swing.JLabel();
        scanFrame_controls_tab2 = new javax.swing.JPanel();
        FTF_barCode_tab2 = new javax.swing.JFormattedTextField();
        B_validate_tab2 = new javax.swing.JButton();
        tab3 = new javax.swing.JPanel();
        L_title_tab3 = new javax.swing.JLabel();
        controls_tab3 = new javax.swing.JSplitPane();
        SP_pupilList_tab3 = new javax.swing.JScrollPane();
        Li_pupilList_tab3 = new javax.swing.JList<>();
        fields_tab3 = new javax.swing.JPanel();
        search_fields_tab3 = new javax.swing.JPanel();
        TF_name_search_tab3 = new javax.swing.JTextField();
        TF_surname_search_tab3 = new javax.swing.JTextField();
        B_validate_search_tab3 = new javax.swing.JButton();
        infos_fields_tab3 = new javax.swing.JPanel();
        L_name_infos_tab3 = new javax.swing.JLabel();
        F_paging1_infos_tab3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        L_surname_infos_tab3 = new javax.swing.JLabel();
        F_paging2_infos_tab3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        SP_bookList_tab3 = new javax.swing.JScrollPane();
        Li_bookList_tab3 = new javax.swing.JList<>();
        P_return_tab3 = new javax.swing.JPanel();
        B_return_infos_tab3 = new javax.swing.JButton();
        managePupil_tab3 = new javax.swing.JPanel();
        B_new_managePupil_tab3 = new javax.swing.JButton();
        B_delete_managePupil_tab3 = new javax.swing.JButton();
        tab4 = new javax.swing.JPanel();
        L_title_tab4 = new javax.swing.JLabel();
        controls_tab4 = new javax.swing.JSplitPane();
        SP_pupilList_tab4 = new javax.swing.JScrollPane();
        Li_pupilList_tab4 = new javax.swing.JList<>();
        fields_tab4 = new javax.swing.JPanel();
        search_fields_tab4 = new javax.swing.JPanel();
        paging_search_fields_tab4 = new javax.swing.JPanel();
        TF_bookTitle_search_tab4 = new javax.swing.JTextField();
        TF_author_search_tab4 = new javax.swing.JTextField();
        TF_theme_search_tab5 = new javax.swing.JTextField();
        TF_keyWords_search_tab6 = new javax.swing.JTextField();
        B_validate_search_tab4 = new javax.swing.JButton();
        infos_fields_tab4 = new javax.swing.JPanel();
        L_bookTitle_infos_tab4 = new javax.swing.JLabel();
        F_paging_infos_tab4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        L_author_infos_tab4 = new javax.swing.JLabel();
        L_theme_infos_tab4 = new javax.swing.JLabel();
        L_pupilName_infos_tab4 = new javax.swing.JLabel();
        P_return_tab4 = new javax.swing.JPanel();
        B_return_infos_tab4 = new javax.swing.JButton();
        manageBook_tab4 = new javax.swing.JPanel();
        B_new_manageBook_tab4 = new javax.swing.JButton();
        B_modify_manageBook_tab4 = new javax.swing.JButton();
        B_delete_manageBook_tab4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new Dimension((int) Math.round(Toolkit.getDefaultToolkit().getScreenSize().getWidth()*0.75), (int) Math.round(Toolkit.getDefaultToolkit().getScreenSize().getHeight()*0.75)));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        background.setBackground(new java.awt.Color(91, 43, 5));
        setVisible(true);
        setPreferredSize(new Dimension(getWidth(), getHeight()));
        getContentPane().add(background, java.awt.BorderLayout.CENTER);
        background.initBackground();
        background.repaint();
        background.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, (int) Math.round(background.getHeight()*0.075)));

        workingArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 226, 165)));
        workingArea.setOpaque(false);
        workingArea.setPreferredSize(new java.awt.Dimension(872, 491));
        workingArea.setPreferredSize(new Dimension((int) Math.round(background.getWidth()*0.85), (int) Math.round(background.getHeight()*0.85)+1));
        workingArea.setLayout(new java.awt.BorderLayout());

        L_title.setFont(littleBird.deriveFont((float) Math.round(workingArea.getPreferredSize().height*0.1)));
        L_title.setForeground(new java.awt.Color(253, 250, 206));
        L_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_title.setText("Bibliotheque de l'école maternelle");
        L_title.setMaximumSize(new java.awt.Dimension(1243, 17));
        L_title.setMinimumSize(new java.awt.Dimension(1243, 17));
        workingArea.add(L_title, java.awt.BorderLayout.NORTH);

        controls.setOpaque(false);
        controls.setPreferredSize(new Dimension(workingArea.getPreferredSize().width, workingArea.getPreferredSize().height-L_title.getPreferredSize().height));
        controls.setLayout(new java.awt.BorderLayout());

        jSeparator1.setBackground(new java.awt.Color(254, 226, 165));
        jSeparator1.setForeground(new java.awt.Color(254, 226, 165));
        jSeparator1.setMaximumSize(new java.awt.Dimension(32767, 1));
        jSeparator1.setMinimumSize(new java.awt.Dimension(4, 1));
        jSeparator1.setPreferredSize(new java.awt.Dimension(4, 1));
        controls.add(jSeparator1, java.awt.BorderLayout.NORTH);

        toggleButtons.setAutoscrolls(true);
        toggleButtons.setOpaque(false);
        toggleButtons.setPreferredSize(new Dimension((int) Math.round(controls.getPreferredSize().width*0.1), controls.getPreferredSize().height));
        toggleButtons.setRequestFocusEnabled(false);
        toggleButtons.setLayout(new javax.swing.BoxLayout(toggleButtons, javax.swing.BoxLayout.PAGE_AXIS));

        TB_card1.setBackground(new java.awt.Color(254, 172, 59));
        TB_card1.setFont(clearLine.deriveFont((float) Math.round(toggleButtons.getPreferredSize().width*0.34)));
        TB_card1.setForeground(new java.awt.Color(254, 226, 165));
        TB_card1.setText("Emprunter");
        TB_card1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 172, 59), 4));
        TB_card1.setContentAreaFilled(false);
        TB_card1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TB_card1.setFocusPainted(false);
        TB_card1.setMargin(new java.awt.Insets(1, 1, 1, 1));
        TB_card1.setMaximumSize(new Dimension(toggleButtons.getPreferredSize().width, toggleButtons.getPreferredSize().width));
        TB_card1.setMinimumSize(new java.awt.Dimension(0, 0));
        TB_card1.setName("card1"); // NOI18N
        toggleButtons.add(TB_card1);

        TB_card2.setBackground(new java.awt.Color(255, 97, 54));
        TB_card2.setFont(clearLine.deriveFont((float) Math.round(toggleButtons.getPreferredSize().width*0.4)));
        TB_card2.setForeground(new java.awt.Color(254, 226, 165));
        TB_card2.setText("Rendre");
        TB_card2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 97, 54), 4));
        TB_card2.setContentAreaFilled(false);
        TB_card2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TB_card2.setFocusPainted(false);
        TB_card2.setMargin(new java.awt.Insets(1, 1, 1, 1));
        TB_card2.setMaximumSize(new Dimension(toggleButtons.getPreferredSize().width, toggleButtons.getPreferredSize().width));
        TB_card2.setMinimumSize(new java.awt.Dimension(0, 0));
        TB_card2.setName("card2"); // NOI18N
        toggleButtons.add(TB_card2);

        TB_card3.setBackground(new java.awt.Color(253, 59, 99));
        TB_card3.setFont(clearLine.deriveFont((float) Math.round(toggleButtons.getPreferredSize().width*0.5)));
        TB_card3.setForeground(new java.awt.Color(254, 226, 165));
        TB_card3.setText("Éleves");
        TB_card3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 59, 99), 4));
        TB_card3.setContentAreaFilled(false);
        TB_card3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TB_card3.setFocusPainted(false);
        TB_card3.setMargin(new java.awt.Insets(1, 1, 1, 1));
        TB_card3.setMaximumSize(new Dimension(toggleButtons.getPreferredSize().width, toggleButtons.getPreferredSize().width));
        TB_card3.setMinimumSize(new java.awt.Dimension(0, 0));
        TB_card3.setName("card3"); // NOI18N
        toggleButtons.add(TB_card3);

        TB_card4.setBackground(new java.awt.Color(218, 94, 238));
        TB_card4.setFont(clearLine.deriveFont((float) Math.round(toggleButtons.getPreferredSize().width*0.5)));
        TB_card4.setForeground(new java.awt.Color(254, 226, 165));
        TB_card4.setText("Livres");
        TB_card4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 94, 238), 4));
        TB_card4.setContentAreaFilled(false);
        TB_card4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TB_card4.setFocusPainted(false);
        TB_card4.setMargin(new java.awt.Insets(1, 1, 1, 1));
        TB_card4.setMaximumSize(new Dimension(toggleButtons.getPreferredSize().width, toggleButtons.getPreferredSize().width));
        TB_card4.setMinimumSize(new java.awt.Dimension(0, 0));
        TB_card4.setName("card4"); // NOI18N
        toggleButtons.add(TB_card4);

        controls.add(toggleButtons, java.awt.BorderLayout.LINE_START);

        mainMenuButtons.setBackground(new java.awt.Color(49, 24, 13));
        mainMenuButtons.setPreferredSize(toggleButtons.getPreferredSize());
        mainMenuButtons.setLayout(new javax.swing.BoxLayout(mainMenuButtons, javax.swing.BoxLayout.PAGE_AXIS));

        B_webSite.setBackground(new java.awt.Color(255, 78, 0));
        B_webSite.setFont(glyphicons.deriveFont((float) Math.round(mainMenuButtons.getPreferredSize().width*0.60)));
        B_webSite.setForeground(new java.awt.Color(254, 226, 165));
        B_webSite.setText("\uE135");
        B_webSite.setToolTipText("Aller sur le site internet");
        B_webSite.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(49, 24, 13), 7));
        B_webSite.setBorderPainted(false);
        B_webSite.setContentAreaFilled(false);
        B_webSite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_webSite.setFocusPainted(false);
        B_webSite.setMaximumSize(new java.awt.Dimension(32767, 32767));
        B_webSite.setPreferredSize(new Dimension(mainMenuButtons.getPreferredSize().width, mainMenuButtons.getPreferredSize().width));
        mainMenuButtons.add(B_webSite);

        B_settings.setBackground(new java.awt.Color(255, 78, 0));
        B_settings.setFont(glyphicons.deriveFont((float) Math.round(mainMenuButtons.getPreferredSize().width*0.60)));
        B_settings.setForeground(new java.awt.Color(254, 226, 165));
        B_settings.setText("\uE019");
        B_settings.setToolTipText("Paramètres");
        B_settings.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(49, 24, 13), 4));
        B_settings.setBorderPainted(false);
        B_settings.setContentAreaFilled(false);
        B_settings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_settings.setFocusPainted(false);
        B_settings.setMaximumSize(new java.awt.Dimension(32767, 32767));
        B_settings.setPreferredSize(new Dimension(mainMenuButtons.getPreferredSize().width, mainMenuButtons.getPreferredSize().width));
        mainMenuButtons.add(B_settings);

        B_help.setBackground(new java.awt.Color(255, 78, 0));
        B_help.setFont(glyphicons.deriveFont((float) Math.round(mainMenuButtons.getPreferredSize().width*0.60)));
        B_help.setForeground(new java.awt.Color(254, 226, 165));
        B_help.setText("\uE085");
        B_help.setToolTipText("À propos…");
        B_help.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(49, 24, 13), 4));
        B_help.setBorderPainted(false);
        B_help.setContentAreaFilled(false);
        B_help.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_help.setFocusPainted(false);
        B_help.setMaximumSize(new java.awt.Dimension(32767, 32767));
        B_help.setPreferredSize(new Dimension(mainMenuButtons.getPreferredSize().width, mainMenuButtons.getPreferredSize().width));
        mainMenuButtons.add(B_help);

        B_quit.setBackground(new java.awt.Color(255, 78, 0));
        B_quit.setFont(glyphicons.deriveFont((float) Math.round(mainMenuButtons.getPreferredSize().width*0.60)));
        B_quit.setForeground(new java.awt.Color(254, 226, 165));
        B_quit.setText("\uE017");
        B_quit.setToolTipText("Quitter");
        B_quit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(49, 24, 13), 4));
        B_quit.setBorderPainted(false);
        B_quit.setContentAreaFilled(false);
        B_quit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B_quit.setFocusPainted(false);
        B_quit.setMaximumSize(new java.awt.Dimension(32767, 32767));
        B_quit.setPreferredSize(new Dimension(mainMenuButtons.getPreferredSize().width, mainMenuButtons.getPreferredSize().width));
        mainMenuButtons.add(B_quit);

        controls.add(mainMenuButtons, java.awt.BorderLayout.LINE_END);

        tabGroups.setOpaque(false);
        tabGroups.setPreferredSize(new Dimension(controls.getPreferredSize().width-2*toggleButtons.getPreferredSize().width, controls.getPreferredSize().height));
        tabGroups.setLayout(new java.awt.CardLayout());

        defaultTab.setOpaque(false);
        defaultTab.setPreferredSize(new Dimension(tabGroups.getPreferredSize().width, tabGroups.getPreferredSize().height));
        defaultTab.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, (int) Math.round(defaultTab.getPreferredSize().height*0.25)));

        P_titles.setMinimumSize(new java.awt.Dimension(861, 50));
        P_titles.setOpaque(false);
        P_titles.setPreferredSize(new java.awt.Dimension(600, 50));
        P_titles.setPreferredSize(new Dimension(defaultTab.getPreferredSize().width, (int) Math.round(defaultTab.getPreferredSize().height*0.31)));

        L_title1.setFont(clearLine.deriveFont((float) Math.round(defaultTab.getPreferredSize().height *0.12)));
        L_title1.setForeground(new java.awt.Color(254, 226, 165));
        L_title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_title1.setText("Bienvenue à la bibliotheque de l'école maternelle!");
        L_title1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        L_title1.setMinimumSize(new java.awt.Dimension(0, 0));
        L_title1.setPreferredSize(new Dimension(P_titles.getPreferredSize().width, (int) Math.round(P_titles.getPreferredSize().height/2)));
        L_title1.setRequestFocusEnabled(false);
        P_titles.add(L_title1);

        L_title2.setFont(clearLine.deriveFont((float) Math.round(defaultTab.getPreferredSize().height *0.10)));
        L_title2.setForeground(new java.awt.Color(254, 226, 165));
        L_title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_title2.setText("Cliquez sur un des onglets à gauche pour commencer");
        L_title2.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        L_title2.setMinimumSize(new java.awt.Dimension(0, 0));
        L_title2.setPreferredSize(new Dimension(P_titles.getPreferredSize().width, (int) Math.round(P_titles.getPreferredSize().height/2)));
        P_titles.add(L_title2);

        defaultTab.add(P_titles);

        tabGroups.add(defaultTab, "card0");

        tab1.setBackground(new java.awt.Color(254, 172, 59));
        tab1.setLayout(new java.awt.BorderLayout());

        L_title_tab1.setFont(clearLine.deriveFont((float) Math.round(defaultTab.getPreferredSize().height *0.12)));
        L_title_tab1.setForeground(new java.awt.Color(255, 233, 184));
        L_title_tab1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_title_tab1.setText("Emprunter un livre");
        L_title_tab1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        L_title_tab1.setMinimumSize(new java.awt.Dimension(0, 0));
        L_title_tab1.setPreferredSize(new Dimension(P_titles.getPreferredSize().width, (int) Math.round(P_titles.getPreferredSize().height/2)));
        L_title_tab1.setRequestFocusEnabled(false);
        tab1.add(L_title_tab1, java.awt.BorderLayout.PAGE_START);

        controls_tab1.setOpaque(false);
        controls_tab1.setPreferredSize(new Dimension(200,0));
        controls_tab1.setLayout(new java.awt.CardLayout());

        fields_tab1.setForeground(new java.awt.Color(49, 20, 13));
        fields_tab1.setToolTipText("");
        fields_tab1.setOpaque(false);
        fields_tab1.setPreferredSize(new Dimension(200,200));
        fields_tab1.setLayout(new javax.swing.BoxLayout(fields_tab1, javax.swing.BoxLayout.PAGE_AXIS));

        fields_tab1_top.setBackground(new java.awt.Color(254, 247, 189));
        fields_tab1_top.setLayout(new javax.swing.BoxLayout(fields_tab1_top, javax.swing.BoxLayout.PAGE_AXIS));

        L_bookTitle_fields_tab1.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.1)));
        L_bookTitle_fields_tab1.setForeground(fields_tab1.getForeground());
        L_bookTitle_fields_tab1.setText("Livre");
        fields_tab1_top.add(L_bookTitle_fields_tab1);

        L_name_fields_tab1.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.05)));
        L_name_fields_tab1.setForeground(fields_tab1.getForeground());
        L_name_fields_tab1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_name_fields_tab1.setText("Nom et prénom de l'emprunteur:");
        L_name_fields_tab1.setMaximumSize(new java.awt.Dimension(32767, 17));
        fields_tab1_top.add(L_name_fields_tab1);

        nameFields_fields_tab1.setAutoscrolls(true);
        nameFields_fields_tab1.setOpaque(false);
        nameFields_fields_tab1.setPreferredSize(new java.awt.Dimension(0, 0));

        SP_pupilList_tab1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(49, 24, 13)), "Liste des élèves", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, L_name_fields_tab1.getFont().deriveFont((float) Math.round(L_name_fields_tab1.getFont().getSize()*0.9)), fields_tab1.getForeground()));
        SP_pupilList_tab1.setForeground(fields_tab1.getForeground());
        SP_pupilList_tab1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        SP_pupilList_tab1.setOpaque(false);

        Li_pupilList_tab1.setBackground(new java.awt.Color(254, 249, 189));
        Li_pupilList_tab1.setFont(L_name_fields_tab1.getFont().deriveFont((float) Math.round(L_name_fields_tab1.getFont().getSize()*0.7)));
        Li_pupilList_tab1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Default" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Li_pupilList_tab1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Li_pupilList_tab1.setCellRenderer(new CustomListCellRenderer());
        Li_pupilList_tab1.setVisibleRowCount(4);
        SP_pupilList_tab1.setViewportView(Li_pupilList_tab1);

        nameFields_fields_tab1.add(SP_pupilList_tab1);

        TF_name_nameFields_tab1.setBackground(new java.awt.Color(249, 176, 74));
        TF_name_nameFields_tab1.setColumns(15);
        TF_name_nameFields_tab1.setFont(L_name_fields_tab1.getFont().deriveFont((float) Math.round(L_name_fields_tab1.getFont().getSize()*0.7)));
        TF_name_nameFields_tab1.setForeground(fields_tab1.getForeground());
        TF_name_nameFields_tab1.setText("NOM");
        TF_name_nameFields_tab1.setBorder(javax.swing.BorderFactory.createLineBorder(fields_tab1.getForeground()));
        TF_name_nameFields_tab1.setCaretColor(new java.awt.Color(49, 24, 13));
        TF_name_nameFields_tab1.setCaretPosition(0);
        TF_name_nameFields_tab1.setOpaque(false);
        nameFields_fields_tab1.add(TF_name_nameFields_tab1);

        TF_surname_nameFields_tab1.setBackground(new java.awt.Color(249, 176, 74));
        TF_surname_nameFields_tab1.setColumns(15);
        TF_surname_nameFields_tab1.setFont(L_name_fields_tab1.getFont().deriveFont((float) Math.round(L_name_fields_tab1.getFont().getSize()*0.7)));
        TF_surname_nameFields_tab1.setForeground(fields_tab1.getForeground());
        TF_surname_nameFields_tab1.setText("Prénom");
        TF_surname_nameFields_tab1.setBorder(javax.swing.BorderFactory.createLineBorder(fields_tab1.getForeground()));
        TF_surname_nameFields_tab1.setCaretColor(new java.awt.Color(49, 24, 13));
        TF_surname_nameFields_tab1.setCaretPosition(0);
        TF_surname_nameFields_tab1.setOpaque(false);
        nameFields_fields_tab1.add(TF_surname_nameFields_tab1);

        fields_tab1_top.add(nameFields_fields_tab1);

        fields_tab1.add(fields_tab1_top);

        fields_tab1_btm.setOpaque(false);

        B_validate_fields_tab1.setBackground(new java.awt.Color(123, 178, 40));
        B_validate_fields_tab1.setFont(L_name_fields_tab1.getFont());
        B_validate_fields_tab1.setForeground(fields_tab1.getForeground());
        B_validate_fields_tab1.setText("   Emprunter   ");
        B_validate_fields_tab1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(90, 150, 0)));
        B_validate_fields_tab1.setContentAreaFilled(false);
        B_validate_fields_tab1.setFocusPainted(false);
        fields_tab1_btm.add(B_validate_fields_tab1);

        fields_tab1.add(fields_tab1_btm);

        controls_tab1.add(fields_tab1, "card2");

        scan_tab1.setForeground(new java.awt.Color(49, 20, 13));
        scan_tab1.setOpaque(false);
        scan_tab1.setLayout(new java.awt.GridLayout(3, 0));
        scan_tab1.add(F_paging_scan_tab1);

        scanFrame_tab1.setBackground(new java.awt.Color(254, 247, 189));
        scanFrame_tab1.setForeground(new java.awt.Color(49, 20, 13));
        scanFrame_tab1.setLayout(new javax.swing.BoxLayout(scanFrame_tab1, javax.swing.BoxLayout.PAGE_AXIS));

        L_scanFrame_title_tab1.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.05)));
        L_scanFrame_title_tab1.setForeground(scan_tab1.getForeground());
        L_scanFrame_title_tab1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_scanFrame_title_tab1.setText("Veuillez scanner le code barre du livre ou le taper dans la zone de texte:");
        scanFrame_tab1.add(L_scanFrame_title_tab1);

        controls_scanFrame_tab1.setOpaque(false);
        controls_scanFrame_tab1.setPreferredSize(new Dimension(scanFrame_tab1.getPreferredSize().width, (int) Math.round(scanFrame_tab1.getPreferredSize().height*0.4)));

        FTF_barCode_tab1.setBackground(new java.awt.Color(249, 176, 74));
        FTF_barCode_tab1.setBorder(javax.swing.BorderFactory.createLineBorder(scan_tab1.getForeground()));
        FTF_barCode_tab1.setColumns(13);
        FTF_barCode_tab1.setForeground(new java.awt.Color(254, 247, 189));
        try {
            FTF_barCode_tab1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FTF_barCode_tab1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FTF_barCode_tab1.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.07)));
        FTF_barCode_tab1.setMargin(new java.awt.Insets(0, 0, 500, 0));
        controls_scanFrame_tab1.add(FTF_barCode_tab1);

        B_validate_scanFrame_tab1.setFont(glyphicons.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.13)));
        B_validate_scanFrame_tab1.setForeground(new java.awt.Color(123, 178, 40));
        B_validate_scanFrame_tab1.setText("\uE084");
        B_validate_scanFrame_tab1.setToolTipText("Valider");
        B_validate_scanFrame_tab1.setBorderPainted(false);
        B_validate_scanFrame_tab1.setContentAreaFilled(false);
        B_validate_scanFrame_tab1.setEnabled(false);
        B_validate_scanFrame_tab1.setFocusPainted(false);
        controls_scanFrame_tab1.add(B_validate_scanFrame_tab1);

        scanFrame_tab1.add(controls_scanFrame_tab1);

        scan_tab1.add(scanFrame_tab1);

        controls_tab1.add(scan_tab1, "card1");

        tab1.add(controls_tab1, java.awt.BorderLayout.CENTER);

        tabGroups.add(tab1, "card1");

        tab2.setBackground(new java.awt.Color(255, 97, 54));
        tab2.setLayout(new java.awt.BorderLayout());

        L_title_tab2.setFont(clearLine.deriveFont((float) Math.round(tabGroups.getPreferredSize().height *0.12)));
        L_title_tab2.setForeground(new java.awt.Color(253, 212, 198));
        L_title_tab2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_title_tab2.setText("Rendre un livre");
        L_title_tab2.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        L_title_tab2.setMinimumSize(new java.awt.Dimension(0, 0));
        L_title_tab2.setPreferredSize(new Dimension(P_titles.getPreferredSize().width, (int) Math.round(P_titles.getPreferredSize().height/2)));
        L_title_tab2.setRequestFocusEnabled(false);
        tab2.add(L_title_tab2, java.awt.BorderLayout.PAGE_START);

        scan_tab2.setForeground(new java.awt.Color(49, 20, 13));
        scan_tab2.setOpaque(false);
        scan_tab2.setLayout(new java.awt.GridLayout(3, 0));
        scan_tab2.add(F_paging_scan_tab2);

        scanFrame_tab2.setBackground(new java.awt.Color(254, 205, 189));
        scanFrame_tab2.setLayout(new javax.swing.BoxLayout(scanFrame_tab2, javax.swing.BoxLayout.PAGE_AXIS));

        L_title_scanFrame_tab2.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.05)));
        L_title_scanFrame_tab2.setForeground(scan_tab2.getForeground());
        L_title_scanFrame_tab2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_title_scanFrame_tab2.setText("Veuillez scanner le code barre du livre ou le taper dans la zone de texte:");
        scanFrame_tab2.add(L_title_scanFrame_tab2);

        scanFrame_controls_tab2.setOpaque(false);
        scanFrame_controls_tab2.setPreferredSize(new Dimension(scanFrame_tab1.getPreferredSize().width, (int) Math.round(scanFrame_tab1.getPreferredSize().height*0.4)));

        FTF_barCode_tab2.setBackground(new java.awt.Color(253, 105, 55));
        FTF_barCode_tab2.setBorder(javax.swing.BorderFactory.createLineBorder(scan_tab2.getForeground()));
        FTF_barCode_tab2.setColumns(13);
        FTF_barCode_tab2.setForeground(new java.awt.Color(254, 226, 189));
        try {
            FTF_barCode_tab2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FTF_barCode_tab2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FTF_barCode_tab2.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.07)));
        scanFrame_controls_tab2.add(FTF_barCode_tab2);

        B_validate_tab2.setFont(glyphicons.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.13)));
        B_validate_tab2.setForeground(new java.awt.Color(123, 178, 40));
        B_validate_tab2.setText("\uE084");
        B_validate_tab2.setToolTipText("Valider");
        B_validate_tab2.setBorderPainted(false);
        B_validate_tab2.setContentAreaFilled(false);
        B_validate_tab2.setEnabled(false);
        B_validate_tab2.setFocusPainted(false);
        scanFrame_controls_tab2.add(B_validate_tab2);

        scanFrame_tab2.add(scanFrame_controls_tab2);

        scan_tab2.add(scanFrame_tab2);

        tab2.add(scan_tab2, java.awt.BorderLayout.CENTER);

        tabGroups.add(tab2, "card2");

        tab3.setBackground(new java.awt.Color(253, 59, 99));
        tab3.setLayout(new java.awt.BorderLayout());

        L_title_tab3.setFont(clearLine.deriveFont((float) Math.round(tabGroups.getPreferredSize().height *0.12)));
        L_title_tab3.setForeground(new java.awt.Color(255, 229, 235));
        L_title_tab3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_title_tab3.setText("Gestion des élèves");
        tab3.add(L_title_tab3, java.awt.BorderLayout.NORTH);

        controls_tab3.setBackground(tab3.getBackground());
        controls_tab3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        controls_tab3.setForeground(new java.awt.Color(253, 206, 216));
        controls_tab3.setContinuousLayout(true);

        SP_pupilList_tab3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 206, 216)), "Élèves ayant emprunté", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.04)), new java.awt.Color(253, 206, 216)));
        SP_pupilList_tab3.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        SP_pupilList_tab3.setOpaque(false);

        Li_pupilList_tab3.setBackground(new java.awt.Color(254, 185, 200));
        Li_pupilList_tab3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 108, 138)));
        Li_pupilList_tab3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Default" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        CustomListCellRenderer cellRenderer_tab3 = new CustomListCellRenderer();
        cellRenderer_tab3.setBackground(new Color(253,157,177));
        cellRenderer_tab3.setForeground(Color.WHITE);
        cellRenderer_tab3.setSelectionForeground(tab3.getBackground());
        Li_pupilList_tab3.setCellRenderer(cellRenderer_tab3);
        SP_pupilList_tab3.setViewportView(Li_pupilList_tab3);

        controls_tab3.setLeftComponent(SP_pupilList_tab3);

        fields_tab3.setOpaque(false);
        fields_tab3.setLayout(new javax.swing.BoxLayout(fields_tab3, javax.swing.BoxLayout.PAGE_AXIS));

        search_fields_tab3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Rechercher un élève :", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.05)), controls_tab3.getForeground()));
        search_fields_tab3.setOpaque(false);

        TF_name_search_tab3.setBackground(controls_tab3.getForeground());
        TF_name_search_tab3.setColumns(15);
        TF_name_search_tab3.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.03)));
        TF_name_search_tab3.setForeground(controls_tab3.getForeground());
        TF_name_search_tab3.setText("NOM");
        TF_name_search_tab3.setBorder(javax.swing.BorderFactory.createLineBorder(controls_tab3.getForeground()));
        TF_name_search_tab3.setCaretColor(controls_tab3.getForeground());
        TF_name_search_tab3.setOpaque(false);
        search_fields_tab3.add(TF_name_search_tab3);

        TF_surname_search_tab3.setBackground(controls_tab3.getForeground());
        TF_surname_search_tab3.setColumns(15);
        TF_surname_search_tab3.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.03)));
        TF_surname_search_tab3.setForeground(controls_tab3.getForeground());
        TF_surname_search_tab3.setText("Prénom");
        TF_surname_search_tab3.setBorder(javax.swing.BorderFactory.createLineBorder(controls_tab3.getForeground()));
        TF_surname_search_tab3.setCaretColor(controls_tab3.getForeground());
        TF_surname_search_tab3.setOpaque(false);
        search_fields_tab3.add(TF_surname_search_tab3);

        B_validate_search_tab3.setBackground(controls_tab3.getForeground());
        B_validate_search_tab3.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.04)));
        B_validate_search_tab3.setForeground(controls_tab3.getForeground());
        B_validate_search_tab3.setText(" Rechercher ");
        B_validate_search_tab3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        B_validate_search_tab3.setContentAreaFilled(false);
        B_validate_search_tab3.setFocusPainted(false);
        search_fields_tab3.add(B_validate_search_tab3);

        fields_tab3.add(search_fields_tab3);

        infos_fields_tab3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        infos_fields_tab3.setOpaque(false);
        infos_fields_tab3.setLayout(new java.awt.GridLayout(4, 2));

        L_name_infos_tab3.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.08)));
        L_name_infos_tab3.setForeground(controls_tab3.getForeground());
        L_name_infos_tab3.setText("NOM");
        infos_fields_tab3.add(L_name_infos_tab3);
        infos_fields_tab3.add(F_paging1_infos_tab3);

        L_surname_infos_tab3.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.06)));
        L_surname_infos_tab3.setForeground(controls_tab3.getForeground());
        L_surname_infos_tab3.setText("Prénom");
        infos_fields_tab3.add(L_surname_infos_tab3);
        infos_fields_tab3.add(F_paging2_infos_tab3);

        SP_bookList_tab3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SP_bookList_tab3.setViewportBorder(null);
        SP_bookList_tab3.setOpaque(false);

        Li_bookList_tab3.setBackground(new java.awt.Color(254, 185, 200));
        Li_bookList_tab3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(254, 108, 138), 2));
        Li_bookList_tab3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Default" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Li_bookList_tab3.setCellRenderer(cellRenderer_tab3);
        SP_bookList_tab3.setViewportView(Li_bookList_tab3);

        infos_fields_tab3.add(SP_bookList_tab3);

        P_return_tab3.setOpaque(false);
        P_return_tab3.setLayout(new java.awt.BorderLayout());

        B_return_infos_tab3.setBackground(new java.awt.Color(123, 178, 40));
        B_return_infos_tab3.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.04)));
        B_return_infos_tab3.setForeground(controls_tab3.getForeground());
        B_return_infos_tab3.setText("  Rendu  ");
        B_return_infos_tab3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(123, 178, 40)));
        B_return_infos_tab3.setContentAreaFilled(false);
        B_return_infos_tab3.setFocusPainted(false);
        P_return_tab3.add(B_return_infos_tab3, java.awt.BorderLayout.LINE_START);

        infos_fields_tab3.add(P_return_tab3);

        fields_tab3.add(infos_fields_tab3);

        controls_tab3.setRightComponent(fields_tab3);

        tab3.add(controls_tab3, java.awt.BorderLayout.CENTER);

        managePupil_tab3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        managePupil_tab3.setOpaque(false);

        B_new_managePupil_tab3.setBackground(controls_tab3.getForeground());
        B_new_managePupil_tab3.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.04)));
        B_new_managePupil_tab3.setForeground(controls_tab3.getForeground());
        B_new_managePupil_tab3.setText(" Nouvel élève ");
        B_new_managePupil_tab3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        B_new_managePupil_tab3.setContentAreaFilled(false);
        B_new_managePupil_tab3.setFocusPainted(false);
        managePupil_tab3.add(B_new_managePupil_tab3);

        B_delete_managePupil_tab3.setBackground(new java.awt.Color(227, 47, 46));
        B_delete_managePupil_tab3.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.04)));
        B_delete_managePupil_tab3.setForeground(controls_tab3.getForeground());
        B_delete_managePupil_tab3.setText(" Supprimer l'élève ");
        B_delete_managePupil_tab3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 47, 46)));
        B_delete_managePupil_tab3.setContentAreaFilled(false);
        B_delete_managePupil_tab3.setFocusPainted(false);
        managePupil_tab3.add(B_delete_managePupil_tab3);

        tab3.add(managePupil_tab3, java.awt.BorderLayout.SOUTH);

        tabGroups.add(tab3, "card3");

        tab4.setBackground(new java.awt.Color(218, 94, 238));
        tab4.setLayout(new java.awt.BorderLayout());

        L_title_tab4.setFont(clearLine.deriveFont((float) Math.round(tabGroups.getPreferredSize().height *0.12)));
        L_title_tab4.setForeground(new java.awt.Color(251, 229, 255));
        L_title_tab4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_title_tab4.setText("Gestion des livres");
        tab4.add(L_title_tab4, java.awt.BorderLayout.NORTH);

        controls_tab4.setBackground(tab4.getBackground());
        controls_tab4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        controls_tab4.setForeground(new java.awt.Color(246, 206, 253));
        controls_tab4.setContinuousLayout(true);

        SP_pupilList_tab4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(246, 206, 253)), "Livres empruntés", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.04)), new java.awt.Color(246, 206, 253)));
        SP_pupilList_tab4.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        SP_pupilList_tab4.setOpaque(false);

        Li_pupilList_tab4.setBackground(new java.awt.Color(244, 185, 254));
        Li_pupilList_tab4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 108, 254)));
        Li_pupilList_tab4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Default" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        CustomListCellRenderer cellRenderer_tab4 = new CustomListCellRenderer();
        cellRenderer_tab4.setBackground(new Color(239,157,253));
        cellRenderer_tab4.setForeground(Color.WHITE);
        cellRenderer_tab4.setSelectionForeground(tab4.getBackground());
        Li_pupilList_tab4.setCellRenderer(cellRenderer_tab4);
        SP_pupilList_tab4.setViewportView(Li_pupilList_tab4);

        controls_tab4.setLeftComponent(SP_pupilList_tab4);

        fields_tab4.setOpaque(false);
        fields_tab4.setLayout(new javax.swing.BoxLayout(fields_tab4, javax.swing.BoxLayout.PAGE_AXIS));

        search_fields_tab4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Rechercher un élève :", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.05)), controls_tab4.getForeground()));
        search_fields_tab4.setOpaque(false);

        paging_search_fields_tab4.setOpaque(false);
        paging_search_fields_tab4.setLayout(new java.awt.GridLayout(2, 0, 3, 3));

        TF_bookTitle_search_tab4.setBackground(controls_tab4.getForeground());
        TF_bookTitle_search_tab4.setColumns(15);
        TF_bookTitle_search_tab4.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.03)));
        TF_bookTitle_search_tab4.setForeground(controls_tab4.getForeground());
        TF_bookTitle_search_tab4.setText("Titre");
        TF_bookTitle_search_tab4.setBorder(javax.swing.BorderFactory.createLineBorder(controls_tab4.getForeground()));
        TF_bookTitle_search_tab4.setCaretColor(controls_tab4.getForeground());
        TF_bookTitle_search_tab4.setOpaque(false);
        paging_search_fields_tab4.add(TF_bookTitle_search_tab4);

        TF_author_search_tab4.setBackground(controls_tab4.getForeground());
        TF_author_search_tab4.setColumns(15);
        TF_author_search_tab4.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.03)));
        TF_author_search_tab4.setForeground(controls_tab4.getForeground());
        TF_author_search_tab4.setText("Auteur");
        TF_author_search_tab4.setBorder(javax.swing.BorderFactory.createLineBorder(controls_tab4.getForeground()));
        TF_author_search_tab4.setCaretColor(controls_tab4.getForeground());
        TF_author_search_tab4.setOpaque(false);
        paging_search_fields_tab4.add(TF_author_search_tab4);

        TF_theme_search_tab5.setBackground(controls_tab4.getForeground());
        TF_theme_search_tab5.setColumns(15);
        TF_theme_search_tab5.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.03)));
        TF_theme_search_tab5.setForeground(controls_tab4.getForeground());
        TF_theme_search_tab5.setText("Thème");
        TF_theme_search_tab5.setBorder(javax.swing.BorderFactory.createLineBorder(controls_tab4.getForeground()));
        TF_theme_search_tab5.setCaretColor(controls_tab4.getForeground());
        TF_theme_search_tab5.setOpaque(false);
        paging_search_fields_tab4.add(TF_theme_search_tab5);

        TF_keyWords_search_tab6.setBackground(controls_tab4.getForeground());
        TF_keyWords_search_tab6.setColumns(15);
        TF_keyWords_search_tab6.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.03)));
        TF_keyWords_search_tab6.setForeground(controls_tab4.getForeground());
        TF_keyWords_search_tab6.setText("Mots clés");
        TF_keyWords_search_tab6.setBorder(javax.swing.BorderFactory.createLineBorder(controls_tab4.getForeground()));
        TF_keyWords_search_tab6.setCaretColor(controls_tab4.getForeground());
        TF_keyWords_search_tab6.setOpaque(false);
        paging_search_fields_tab4.add(TF_keyWords_search_tab6);

        search_fields_tab4.add(paging_search_fields_tab4);

        B_validate_search_tab4.setBackground(controls_tab4.getForeground());
        B_validate_search_tab4.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.04)));
        B_validate_search_tab4.setForeground(controls_tab4.getForeground());
        B_validate_search_tab4.setText(" Rechercher ");
        B_validate_search_tab4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        B_validate_search_tab4.setContentAreaFilled(false);
        B_validate_search_tab4.setFocusPainted(false);
        search_fields_tab4.add(B_validate_search_tab4);

        fields_tab4.add(search_fields_tab4);

        infos_fields_tab4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        infos_fields_tab4.setOpaque(false);
        infos_fields_tab4.setLayout(new java.awt.GridLayout(4, 2));

        L_bookTitle_infos_tab4.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.08)));
        L_bookTitle_infos_tab4.setForeground(controls_tab4.getForeground());
        L_bookTitle_infos_tab4.setText("Titre");
        infos_fields_tab4.add(L_bookTitle_infos_tab4);
        infos_fields_tab4.add(F_paging_infos_tab4);

        L_author_infos_tab4.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.06)));
        L_author_infos_tab4.setForeground(controls_tab4.getForeground());
        L_author_infos_tab4.setText("Auteur");
        infos_fields_tab4.add(L_author_infos_tab4);

        L_theme_infos_tab4.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.06)));
        L_theme_infos_tab4.setForeground(controls_tab4.getForeground());
        L_theme_infos_tab4.setText("Thème");
        infos_fields_tab4.add(L_theme_infos_tab4);

        L_pupilName_infos_tab4.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.05)));
        L_pupilName_infos_tab4.setForeground(controls_tab4.getForeground());
        L_pupilName_infos_tab4.setText("Emprunté par...");
        infos_fields_tab4.add(L_pupilName_infos_tab4);

        P_return_tab4.setOpaque(false);
        P_return_tab4.setLayout(new java.awt.BorderLayout());

        B_return_infos_tab4.setBackground(new java.awt.Color(123, 178, 40));
        B_return_infos_tab4.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.04)));
        B_return_infos_tab4.setForeground(controls_tab4.getForeground());
        B_return_infos_tab4.setText("  Rendu  ");
        B_return_infos_tab4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(123, 178, 40)));
        B_return_infos_tab4.setContentAreaFilled(false);
        B_return_infos_tab4.setFocusPainted(false);
        P_return_tab4.add(B_return_infos_tab4, java.awt.BorderLayout.LINE_START);

        infos_fields_tab4.add(P_return_tab4);

        fields_tab4.add(infos_fields_tab4);

        controls_tab4.setRightComponent(fields_tab4);

        tab4.add(controls_tab4, java.awt.BorderLayout.CENTER);

        manageBook_tab4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));
        manageBook_tab4.setOpaque(false);

        B_new_manageBook_tab4.setBackground(controls_tab4.getForeground());
        B_new_manageBook_tab4.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.04)));
        B_new_manageBook_tab4.setForeground(controls_tab4.getForeground());
        B_new_manageBook_tab4.setText(" Nouveau livre ");
        B_new_manageBook_tab4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        B_new_manageBook_tab4.setContentAreaFilled(false);
        B_new_manageBook_tab4.setFocusPainted(false);
        manageBook_tab4.add(B_new_manageBook_tab4);

        B_modify_manageBook_tab4.setBackground(controls_tab4.getForeground());
        B_modify_manageBook_tab4.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.04)));
        B_modify_manageBook_tab4.setForeground(controls_tab4.getForeground());
        B_modify_manageBook_tab4.setText(" Modifier le livre ");
        B_modify_manageBook_tab4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        B_modify_manageBook_tab4.setContentAreaFilled(false);
        B_modify_manageBook_tab4.setFocusPainted(false);
        manageBook_tab4.add(B_modify_manageBook_tab4);

        B_delete_manageBook_tab4.setBackground(new java.awt.Color(227, 47, 46));
        B_delete_manageBook_tab4.setFont(maritime.deriveFont((float) Math.round(tabGroups.getPreferredSize().height*0.04)));
        B_delete_manageBook_tab4.setForeground(controls_tab4.getForeground());
        B_delete_manageBook_tab4.setText(" Supprimer le livre ");
        B_delete_manageBook_tab4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 47, 46)));
        B_delete_manageBook_tab4.setContentAreaFilled(false);
        B_delete_manageBook_tab4.setFocusPainted(false);
        manageBook_tab4.add(B_delete_manageBook_tab4);

        tab4.add(manageBook_tab4, java.awt.BorderLayout.PAGE_END);

        tabGroups.add(tab4, "card4");

        controls.add(tabGroups, java.awt.BorderLayout.CENTER);

        workingArea.add(controls, java.awt.BorderLayout.CENTER);

        background.add(workingArea);
        background.validate();

        getContentPane().add(background, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            DBConnection.getInstance().getConnection().close();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosed

    public JButton getB_help() {
        return B_help;
    }

    public JButton getB_quit() {
        return B_quit;
    }

    public JButton getB_settings() {
        return B_settings;
    }

    public JToggleButton getTB_card1() {
        return TB_card1;
    }

    public JToggleButton getTB_card2() {
        return TB_card2;
    }

    public JToggleButton getTB_card3() {
        return TB_card3;
    }

    public JToggleButton getTB_card4() {
        return TB_card4;
    }

    public CardLayout getTabGroupsLayout() {
        return (CardLayout) tabGroups.getLayout();
    }

    public JPanel getTabGroups() {
        return tabGroups;
    }

    public JPanel getToggleButtons() {
        return toggleButtons;
    }

    public JButton getB_webSite() {
        return B_webSite;
    }
    
    
    private Font littleBird;
    private Font clearLine;
    private Font glyphicons;
    private Font maritime;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_delete_manageBook_tab4;
    private javax.swing.JButton B_delete_managePupil_tab3;
    private javax.swing.JButton B_help;
    private javax.swing.JButton B_modify_manageBook_tab4;
    private javax.swing.JButton B_new_manageBook_tab4;
    private javax.swing.JButton B_new_managePupil_tab3;
    private javax.swing.JButton B_quit;
    private javax.swing.JButton B_return_infos_tab3;
    private javax.swing.JButton B_return_infos_tab4;
    private javax.swing.JButton B_settings;
    private javax.swing.JButton B_validate_fields_tab1;
    private javax.swing.JButton B_validate_scanFrame_tab1;
    private javax.swing.JButton B_validate_search_tab3;
    private javax.swing.JButton B_validate_search_tab4;
    private javax.swing.JButton B_validate_tab2;
    private javax.swing.JButton B_webSite;
    private javax.swing.JFormattedTextField FTF_barCode_tab1;
    private javax.swing.JFormattedTextField FTF_barCode_tab2;
    private javax.swing.Box.Filler F_paging1_infos_tab3;
    private javax.swing.Box.Filler F_paging2_infos_tab3;
    private javax.swing.Box.Filler F_paging_infos_tab4;
    private javax.swing.Box.Filler F_paging_scan_tab1;
    private javax.swing.Box.Filler F_paging_scan_tab2;
    private javax.swing.JLabel L_author_infos_tab4;
    private javax.swing.JLabel L_bookTitle_fields_tab1;
    private javax.swing.JLabel L_bookTitle_infos_tab4;
    private javax.swing.JLabel L_name_fields_tab1;
    private javax.swing.JLabel L_name_infos_tab3;
    private javax.swing.JLabel L_pupilName_infos_tab4;
    private javax.swing.JLabel L_scanFrame_title_tab1;
    private javax.swing.JLabel L_surname_infos_tab3;
    private javax.swing.JLabel L_theme_infos_tab4;
    private javax.swing.JLabel L_title;
    private javax.swing.JLabel L_title1;
    private javax.swing.JLabel L_title2;
    private javax.swing.JLabel L_title_scanFrame_tab2;
    private javax.swing.JLabel L_title_tab1;
    private javax.swing.JLabel L_title_tab2;
    private javax.swing.JLabel L_title_tab3;
    private javax.swing.JLabel L_title_tab4;
    private javax.swing.JList<String> Li_bookList_tab3;
    private javax.swing.JList<String> Li_pupilList_tab1;
    private javax.swing.JList<String> Li_pupilList_tab3;
    private javax.swing.JList<String> Li_pupilList_tab4;
    private javax.swing.JPanel P_return_tab3;
    private javax.swing.JPanel P_return_tab4;
    private javax.swing.JPanel P_titles;
    private javax.swing.JScrollPane SP_bookList_tab3;
    private javax.swing.JScrollPane SP_pupilList_tab1;
    private javax.swing.JScrollPane SP_pupilList_tab3;
    private javax.swing.JScrollPane SP_pupilList_tab4;
    private javax.swing.JToggleButton TB_card1;
    private javax.swing.JToggleButton TB_card2;
    private javax.swing.JToggleButton TB_card3;
    private javax.swing.JToggleButton TB_card4;
    private javax.swing.JTextField TF_author_search_tab4;
    private javax.swing.JTextField TF_bookTitle_search_tab4;
    private javax.swing.JTextField TF_keyWords_search_tab6;
    private javax.swing.JTextField TF_name_nameFields_tab1;
    private javax.swing.JTextField TF_name_search_tab3;
    private javax.swing.JTextField TF_surname_nameFields_tab1;
    private javax.swing.JTextField TF_surname_search_tab3;
    private javax.swing.JTextField TF_theme_search_tab5;
    private bibliotheque.view.customComponents.BgPanel background;
    private javax.swing.JPanel controls;
    private javax.swing.JPanel controls_scanFrame_tab1;
    private javax.swing.JPanel controls_tab1;
    private javax.swing.JSplitPane controls_tab3;
    private javax.swing.JSplitPane controls_tab4;
    private javax.swing.JPanel defaultTab;
    private javax.swing.JPanel fields_tab1;
    private javax.swing.JPanel fields_tab1_btm;
    private javax.swing.JPanel fields_tab1_top;
    private javax.swing.JPanel fields_tab3;
    private javax.swing.JPanel fields_tab4;
    private javax.swing.JPanel infos_fields_tab3;
    private javax.swing.JPanel infos_fields_tab4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainMenuButtons;
    private javax.swing.JPanel manageBook_tab4;
    private javax.swing.JPanel managePupil_tab3;
    private javax.swing.JPanel nameFields_fields_tab1;
    private javax.swing.JPanel paging_search_fields_tab4;
    private javax.swing.JPanel scanFrame_controls_tab2;
    private javax.swing.JPanel scanFrame_tab1;
    private javax.swing.JPanel scanFrame_tab2;
    private javax.swing.JPanel scan_tab1;
    private javax.swing.JPanel scan_tab2;
    private javax.swing.JPanel search_fields_tab3;
    private javax.swing.JPanel search_fields_tab4;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab4;
    private javax.swing.JPanel tabGroups;
    private javax.swing.JPanel toggleButtons;
    private javax.swing.JPanel workingArea;
    // End of variables declaration//GEN-END:variables
}
