
package bibliotheque.view;

import bibliotheque.view.customComponents.BgPanel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author shiro
 */
public class NewBook extends javax.swing.JFrame {

    public NewBook() {
        try {
            littleBird = Font.createFont(Font.TRUETYPE_FONT, getClass().getClassLoader().getResourceAsStream("LittleBird.ttf"));
            glyphicons = Font.createFont(Font.TRUETYPE_FONT, getClass().getClassLoader().getResourceAsStream("glyphicons.ttf"));
            maritime = Font.createFont(Font.TRUETYPE_FONT, getClass().getClassLoader().getResourceAsStream("MaritimeTropicalNeue.ttf"));
        } catch (FontFormatException | IOException ex) {
            Logger.getLogger(BgPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        setUndecorated(true);
        initComponents();
        setVisible(true);
        B_cancel.requestFocusInWindow();
        mainPanel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        L_title = new javax.swing.JLabel();
        controls = new javax.swing.JPanel();
        TF_title = new javax.swing.JTextField();
        TF_author = new javax.swing.JTextField();
        TF_barCode = new javax.swing.JTextField();
        TF_theme = new javax.swing.JTextField();
        TF_keywords = new javax.swing.JTextField();
        buttons = new javax.swing.JPanel();
        B_validate = new javax.swing.JButton();
        B_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new Color(0,0,0,0.3f));
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, (int) Math.round(Toolkit.getDefaultToolkit().getScreenSize().getHeight()*0.2)));

        mainPanel.setBackground(new java.awt.Color(218, 94, 238));
        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 206, 216), 5));
        mainPanel.setForeground(new java.awt.Color(246, 206, 253));
        mainPanel.setPreferredSize(new Dimension((int) Math.round(Toolkit.getDefaultToolkit().getScreenSize().getWidth()*0.6), (int) Math.round(Toolkit.getDefaultToolkit().getScreenSize().getHeight()*0.6)));
        mainPanel.setLayout(new java.awt.BorderLayout());

        L_title.setFont(littleBird.deriveFont((float) Math.round(mainPanel.getPreferredSize().height*0.18)));
        L_title.setForeground(mainPanel.getForeground());
        L_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_title.setText("Nouveau livre");
        mainPanel.add(L_title, java.awt.BorderLayout.NORTH);

        controls.setBackground(mainPanel.getBackground());
        controls.setForeground(mainPanel.getForeground());
        controls.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(controls.getForeground()), BorderFactory.createEmptyBorder(1, ((int) Math.round(mainPanel.getPreferredSize().height*0.05)), 1, ((int) Math.round(mainPanel.getPreferredSize().height*0.05)))));
        controls.setOpaque(false);
        controls.setLayout(new java.awt.GridLayout(0, 1, 0, (int) Math.round(mainPanel.getPreferredSize().height*0.01)));

        TF_title.setBackground(controls.getBackground());
        TF_title.setFont(maritime.deriveFont((float) Math.round(mainPanel.getPreferredSize().height*0.09)));
        TF_title.setForeground(controls.getForeground());
        TF_title.setText("Titre");
        TF_title.setToolTipText("Titre");
        TF_title.setBorder(null);
        TF_title.setCaretColor(controls.getForeground());
        controls.add(TF_title);

        TF_author.setBackground(controls.getBackground());
        TF_author.setFont(maritime.deriveFont((float) Math.round(mainPanel.getPreferredSize().height*0.09)));
        TF_author.setForeground(controls.getForeground());
        TF_author.setText("Auteur");
        TF_author.setToolTipText("Auteur");
        TF_author.setBorder(null);
        TF_author.setCaretColor(controls.getForeground());
        controls.add(TF_author);

        TF_barCode.setBackground(controls.getBackground());
        TF_barCode.setFont(maritime.deriveFont((float) Math.round(mainPanel.getPreferredSize().height*0.09)));
        TF_barCode.setForeground(controls.getForeground());
        TF_barCode.setText("Code-barre/Code ISBN");
        TF_barCode.setToolTipText("Code-barre/Code ISBN");
        TF_barCode.setBorder(null);
        TF_barCode.setCaretColor(controls.getForeground());
        controls.add(TF_barCode);

        TF_theme.setBackground(controls.getBackground());
        TF_theme.setFont(maritime.deriveFont((float) Math.round(mainPanel.getPreferredSize().height*0.09)));
        TF_theme.setForeground(controls.getForeground());
        TF_theme.setText("Thème");
        TF_theme.setToolTipText("Thème");
        TF_theme.setBorder(null);
        TF_theme.setCaretColor(controls.getForeground());
        controls.add(TF_theme);

        TF_keywords.setBackground(controls.getBackground());
        TF_keywords.setFont(maritime.deriveFont((float) Math.round(mainPanel.getPreferredSize().height*0.09)));
        TF_keywords.setForeground(controls.getForeground());
        TF_keywords.setText("Mots-clés");
        TF_keywords.setToolTipText("Mots-clés");
        TF_keywords.setBorder(null);
        TF_keywords.setCaretColor(controls.getForeground());
        controls.add(TF_keywords);

        mainPanel.add(controls, java.awt.BorderLayout.CENTER);

        buttons.setOpaque(false);

        B_validate.setFont(glyphicons.deriveFont((float) Math.round(mainPanel.getPreferredSize().height*0.13)));
        B_validate.setForeground(new java.awt.Color(123, 178, 40));
        B_validate.setText("\uE084");
        B_validate.setToolTipText("Valider");
        B_validate.setBorderPainted(false);
        B_validate.setContentAreaFilled(false);
        B_validate.setFocusPainted(false);
        buttons.add(B_validate);

        B_cancel.setFont(glyphicons.deriveFont((float) Math.round(mainPanel.getPreferredSize().height*0.13)));
        B_cancel.setForeground(new java.awt.Color(227, 47, 46));
        B_cancel.setText("\uE083");
        B_cancel.setToolTipText("Annuler");
        B_cancel.setBorderPainted(false);
        B_cancel.setContentAreaFilled(false);
        B_cancel.setFocusPainted(false);
        buttons.add(B_cancel);

        mainPanel.add(buttons, java.awt.BorderLayout.PAGE_END);

        mainPanel.setVisible(false);

        getContentPane().add(mainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showErrorMessage(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Erreur", JOptionPane.ERROR_MESSAGE);
    }
    
    public void showMessage(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }
    
    public JButton getB_validate() {
        return B_validate;
    }

    public JButton getB_cancel() {
        return B_cancel;
    }

    public JTextField getTF_author() {
        return TF_author;
    }

    public JTextField getTF_barCode() {
        return TF_barCode;
    }

    public JTextField getTF_keywords() {
        return TF_keywords;
    }

    public JTextField getTF_theme() {
        return TF_theme;
    }

    public JTextField getTF_title() {
        return TF_title;
    }

    
    
    private Font littleBird, glyphicons, maritime;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_cancel;
    private javax.swing.JButton B_validate;
    private javax.swing.JLabel L_title;
    private javax.swing.JTextField TF_author;
    private javax.swing.JTextField TF_barCode;
    private javax.swing.JTextField TF_keywords;
    private javax.swing.JTextField TF_theme;
    private javax.swing.JTextField TF_title;
    private javax.swing.JPanel buttons;
    private javax.swing.JPanel controls;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
