
package bibliotheque.view;

import bibliotheque.view.customComponents.BgPanel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author shiro
 */
public class NewPupil extends javax.swing.JFrame {

    public NewPupil() {
        try {
            littleBird = Font.createFont(Font.TRUETYPE_FONT, getClass().getClassLoader().getResourceAsStream("LittleBird.ttf"));
            glyphicons = Font.createFont(Font.TRUETYPE_FONT, getClass().getClassLoader().getResourceAsStream("glyphicons.ttf"));
            maritime = Font.createFont(Font.TRUETYPE_FONT, getClass().getClassLoader().getResourceAsStream("MaritimeTropicalNeue.ttf"));
        } catch (FontFormatException | IOException ex) {
            Logger.getLogger(BgPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        setUndecorated(true);
        initComponents();
        setVisible(true);
        B_cancel.requestFocusInWindow();
        mainPanel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        L_title = new javax.swing.JLabel();
        controls = new javax.swing.JPanel();
        TF_name = new javax.swing.JTextField();
        TF_surname = new javax.swing.JTextField();
        buttons = new javax.swing.JPanel();
        B_validate = new javax.swing.JButton();
        B_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new Color(0,0,0,0.3f));
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, (int) Math.round(Toolkit.getDefaultToolkit().getScreenSize().getHeight()*0.2)));

        mainPanel.setBackground(new java.awt.Color(253, 59, 99));
        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 206, 216)));
        mainPanel.setForeground(new java.awt.Color(253, 206, 216));
        mainPanel.setPreferredSize(new Dimension((int) Math.round(Toolkit.getDefaultToolkit().getScreenSize().getWidth()*0.6), (int) Math.round(Toolkit.getDefaultToolkit().getScreenSize().getHeight()*0.6)));
        mainPanel.setLayout(new java.awt.BorderLayout());

        L_title.setFont(littleBird.deriveFont((float) Math.round(mainPanel.getPreferredSize().height*0.18)));
        L_title.setForeground(new java.awt.Color(253, 206, 216));
        L_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_title.setText("Nouvel élève");
        mainPanel.add(L_title, java.awt.BorderLayout.NORTH);

        controls.setBackground(mainPanel.getBackground());
        controls.setForeground(mainPanel.getForeground());
        controls.setOpaque(false);
        controls.setLayout(new java.awt.GridLayout(2, 0));

        TF_name.setBackground(controls.getBackground());
        TF_name.setFont(maritime.deriveFont((float) Math.round(mainPanel.getPreferredSize().height*0.15)));
        TF_name.setForeground(controls.getForeground());
        TF_name.setText("Nom");
        TF_name.setToolTipText("Nom");
        TF_name.setBorder(null);
        TF_name.setCaretColor(controls.getForeground());
        controls.add(TF_name);

        TF_surname.setBackground(controls.getBackground());
        TF_surname.setFont(maritime.deriveFont((float) Math.round(mainPanel.getPreferredSize().height*0.12)));
        TF_surname.setForeground(controls.getForeground());
        TF_surname.setText("Prénom");
        TF_surname.setToolTipText("Prénom");
        TF_surname.setBorder(null);
        TF_surname.setCaretColor(controls.getForeground());
        controls.add(TF_surname);

        mainPanel.add(controls, java.awt.BorderLayout.CENTER);

        buttons.setOpaque(false);

        B_validate.setFont(glyphicons.deriveFont((float) Math.round(mainPanel.getPreferredSize().height*0.13)));
        B_validate.setForeground(new java.awt.Color(123, 178, 40));
        B_validate.setText("\uE084");
        B_validate.setToolTipText("Valider");
        B_validate.setBorderPainted(false);
        B_validate.setContentAreaFilled(false);
        B_validate.setFocusPainted(false);
        buttons.add(B_validate);

        B_cancel.setFont(glyphicons.deriveFont((float) Math.round(mainPanel.getPreferredSize().height*0.13)));
        B_cancel.setForeground(new java.awt.Color(227, 47, 46));
        B_cancel.setText("\uE083");
        B_cancel.setToolTipText("Annuler");
        B_cancel.setBorderPainted(false);
        B_cancel.setContentAreaFilled(false);
        B_cancel.setFocusPainted(false);
        buttons.add(B_cancel);

        mainPanel.add(buttons, java.awt.BorderLayout.PAGE_END);

        mainPanel.setVisible(false);

        getContentPane().add(mainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showErrorMessage(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Erreur", JOptionPane.ERROR_MESSAGE);
    }
    
    public void showMessage(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }
    
    public JButton getB_validate() {
        return B_validate;
    }

    public JButton getB_cancel() {
        return B_cancel;
    }

    public JTextField getTF_name() {
        return TF_name;
    }

    public JTextField getTF_surname() {
        return TF_surname;
    }

    
    private Font littleBird, glyphicons, maritime;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_cancel;
    private javax.swing.JButton B_validate;
    private javax.swing.JLabel L_title;
    private javax.swing.JTextField TF_name;
    private javax.swing.JTextField TF_surname;
    private javax.swing.JPanel buttons;
    private javax.swing.JPanel controls;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
