/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bibliotheque.view;

import bibliotheque.view.customComponents.BgPanel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JList;

/**
 *
 * @author shiro
 */
public class SearchResult extends javax.swing.JFrame {

    private JList model;
    public SearchResult(JList model) {
        
        this.model = model;
        try {
            littleBird = Font.createFont(Font.TRUETYPE_FONT, getClass().getClassLoader().getResourceAsStream("LittleBird.ttf"));
            glyphicons = Font.createFont(Font.TRUETYPE_FONT, getClass().getClassLoader().getResourceAsStream("glyphicons.ttf"));
        } catch (FontFormatException | IOException ex) {
            Logger.getLogger(BgPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        setUndecorated(true);
        initComponents();
        setVisible(true);
        jPanel1.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SP_pupilList_tab3 = new javax.swing.JScrollPane();
        Li_pupilList_tab3 = new javax.swing.JList<>();
        L_title = new javax.swing.JLabel();
        B_validate_tab2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new Color(0,0,0,0.3f));
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, (int) Math.round(Toolkit.getDefaultToolkit().getScreenSize().getHeight()*0.2)));

        jPanel1.setBackground(model.getForeground());
        jPanel1.setPreferredSize(new Dimension((int) Math.round(Toolkit.getDefaultToolkit().getScreenSize().getWidth()*0.4), (int) Math.round(Toolkit.getDefaultToolkit().getScreenSize().getHeight()*0.4)));
        jPanel1.setLayout(new java.awt.BorderLayout());

        SP_pupilList_tab3.setBorder(javax.swing.BorderFactory.createLineBorder(model.getBackground()));
        SP_pupilList_tab3.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        SP_pupilList_tab3.setOpaque(false);

        Li_pupilList_tab3.setBackground(model.getBackground());
        Li_pupilList_tab3.setBorder(model.getBorder());
        Li_pupilList_tab3.setCellRenderer(model.getCellRenderer());
        SP_pupilList_tab3.setViewportView(Li_pupilList_tab3);

        jPanel1.add(SP_pupilList_tab3, java.awt.BorderLayout.CENTER);

        L_title.setFont(littleBird.deriveFont((float) Math.round(jPanel1.getPreferredSize().height*0.1)));
        L_title.setForeground(new java.awt.Color(253, 250, 206));
        L_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_title.setText("Résultat de la recherche");
        jPanel1.add(L_title, java.awt.BorderLayout.NORTH);

        B_validate_tab2.setFont(glyphicons.deriveFont((float) Math.round(jPanel1.getPreferredSize().height*0.13)));
        B_validate_tab2.setForeground(new java.awt.Color(123, 178, 40));
        B_validate_tab2.setText("\uE084");
        B_validate_tab2.setToolTipText("Valider");
        B_validate_tab2.setBorderPainted(false);
        B_validate_tab2.setContentAreaFilled(false);
        B_validate_tab2.setEnabled(false);
        B_validate_tab2.setFocusPainted(false);
        jPanel1.add(B_validate_tab2, java.awt.BorderLayout.PAGE_END);

        jPanel1.setVisible(false);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private Font littleBird, glyphicons;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_validate_tab2;
    private javax.swing.JLabel L_title;
    private javax.swing.JList<String> Li_pupilList_tab3;
    private javax.swing.JScrollPane SP_pupilList_tab3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
